- name: Start control plane nodes
  community.general.proxmox_kvm:
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ item.vmid + vmbase }}"
    state: started
  with_items: "{{ masters }}"
